services:
  - type: web
    name: et-ai-concierge
    runtime: image
    repo: https://github.com/paras-paul25/Economic-Times_2nd-round
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
